# Generated by Django 2.2.6 on 2019-11-15 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_people', to='lore.Character')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_people', to='lore.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='related',
            field=models.ManyToManyField(related_name='related_to', through='lore.Relationship', to='lore.Character'),
        ),
    ]
