# Generated by Django 2.2.6 on 2019-11-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathere', to='lore.Character'),
        ),
        migrations.AddField(
            model_name='character',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lore.Character'),
        ),
        migrations.CreateModel(
            name='Siblings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a', to='lore.Character')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='b', to='lore.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='siblings',
            field=models.ManyToManyField(related_name='sibling', through='lore.Siblings', to='lore.Character'),
        ),
    ]
