# Generated by Django 2.2.6 on 2019-11-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0002_auto_20191115_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_father', to='lore.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_mother', to='lore.Character'),
        ),
    ]
