# Generated by Django 2.2.6 on 2019-11-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0003_auto_20191115_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Siblings',
            new_name='Sibling',
        ),
    ]
