# Generated by Django 2.2.6 on 2019-11-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0006_auto_20191115_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='relatedCharacters',
        ),
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='lore.House'),
        ),
    ]
