# Generated by Django 2.2.6 on 2019-11-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0007_auto_20191115_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='house',
            name='logoURL',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='house',
            name='words',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Allegiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a', to='lore.House')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='b', to='lore.House')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='allegiances',
            field=models.ManyToManyField(related_name='allegiance', through='lore.Allegiance', to='lore.House'),
        ),
    ]
