# Generated by Django 2.2.6 on 2019-11-15 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0008_auto_20191115_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_in_house', to='lore.House'),
        ),
    ]
