# Generated by Django 2.2.6 on 2019-11-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0009_auto_20191116_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='siblings',
            field=models.ManyToManyField(related_name='_siblings', through='lore.Sibling', to='lore.Character'),
        ),
    ]
