# Generated by Django 2.2.6 on 2019-11-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allegiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(default='', max_length=500)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_father', to='app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a', to='app.Character')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='b', to='app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_people', to='app.Character')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_people', to='app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('words', models.CharField(default='', max_length=500)),
                ('logoURL', models.CharField(default='', max_length=500)),
                ('allegiances', models.ManyToManyField(related_name='allegiance', through='app.Allegiance', to='app.House')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_in_house', to='app.House'),
        ),
        migrations.AddField(
            model_name='character',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_mother', to='app.Character'),
        ),
        migrations.AddField(
            model_name='character',
            name='related',
            field=models.ManyToManyField(related_name='related_to', through='app.Relationship', to='app.Character'),
        ),
        migrations.AddField(
            model_name='character',
            name='siblings',
            field=models.ManyToManyField(related_name='_siblings', through='app.Sibling', to='app.Character'),
        ),
        migrations.AddField(
            model_name='allegiance',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='a', to='app.House'),
        ),
        migrations.AddField(
            model_name='allegiance',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='b', to='app.House'),
        ),
    ]
