# Generated by Django 2.2.6 on 2019-11-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='originalPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='op', to='app.Post'),
        ),
    ]
