# Generated by Django 2.2.6 on 2019-11-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_thread_originalpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('directedBy', models.CharField(max_length=250)),
                ('season', models.IntegerField()),
            ],
        ),
    ]
