# Generated by Django 2.2.6 on 2019-11-17 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appearances', to='app.Character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='episode_appearance', to='app.Episode')),
            ],
        ),
    ]
