# Generated by Django 2.2.6 on 2019-11-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_character_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='numberInSeason',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
