# Generated by Django 2.2.6 on 2019-11-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_episode_numberinseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='originalPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op', to='app.Post'),
        ),
    ]
