# Generated by Django 2.2.6 on 2019-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191118_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
